CREATE DATABASE IF NOT EXISTS zioraa;
USE zz;
CREATE TABLE IF NOT EXISTS users (uid INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) NOT NULL,pass VARCHAR(255) NOT NULL,desig CHAR(1), address VARCHAR(255),email VARCHAR(100) UNIQUE,phone VARCHAR(13));
CREATE TABLE IF NOT EXISTS products (pid INT AUTO_INCREMENT PRIMARY KEY,prodname VARCHAR(100) NOT NULL,stock INT NOT NULL,price FLOAT NOT NULL,offer VARCHAR(50),sold INT DEFAULT 0,supplier VARCHAR(100),img VARCHAR(255));
CREATE TABLE IF NOT EXISTS orders (oid INT AUTO_INCREMENT PRIMARY KEY,uid INT,pid INT,price FLOAT NOT NULL,status VARCHAR(30),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS wish (wid INT AUTO_INCREMENT PRIMARY KEY, uid INT, pid INt);
CREATE TABLE IF NOT EXISTS img (iid INT AUTO_INCREMENT PRIMARY KEY, pid INT, link varchar(255));
